export default [
{
"login": "Terenceonye",
"id": 11439251,
"node_id": "MDQ6VXNlcjExNDM5MjUx",
"avatar_url": "https://avatars.githubusercontent.com/u/11439251?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Terenceonye",
"html_url": "https://github.com/Terenceonye",
"followers_url": "https://api.github.com/users/Terenceonye/followers",
"following_url": "https://api.github.com/users/Terenceonye/following{/other_user}",
"gists_url": "https://api.github.com/users/Terenceonye/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Terenceonye/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Terenceonye/subscriptions",
"organizations_url": "https://api.github.com/users/Terenceonye/orgs",
"repos_url": "https://api.github.com/users/Terenceonye/repos",
"events_url": "https://api.github.com/users/Terenceonye/events{/privacy}",
"received_events_url": "https://api.github.com/users/Terenceonye/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Elisvobs",
"id": 37229539,
"node_id": "MDQ6VXNlcjM3MjI5NTM5",
"avatar_url": "https://avatars.githubusercontent.com/u/37229539?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Elisvobs",
"html_url": "https://github.com/Elisvobs",
"followers_url": "https://api.github.com/users/Elisvobs/followers",
"following_url": "https://api.github.com/users/Elisvobs/following{/other_user}",
"gists_url": "https://api.github.com/users/Elisvobs/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Elisvobs/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Elisvobs/subscriptions",
"organizations_url": "https://api.github.com/users/Elisvobs/orgs",
"repos_url": "https://api.github.com/users/Elisvobs/repos",
"events_url": "https://api.github.com/users/Elisvobs/events{/privacy}",
"received_events_url": "https://api.github.com/users/Elisvobs/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Ajgesh",
"id": 40598406,
"node_id": "MDQ6VXNlcjQwNTk4NDA2",
"avatar_url": "https://avatars.githubusercontent.com/u/40598406?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Ajgesh",
"html_url": "https://github.com/Ajgesh",
"followers_url": "https://api.github.com/users/Ajgesh/followers",
"following_url": "https://api.github.com/users/Ajgesh/following{/other_user}",
"gists_url": "https://api.github.com/users/Ajgesh/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Ajgesh/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Ajgesh/subscriptions",
"organizations_url": "https://api.github.com/users/Ajgesh/orgs",
"repos_url": "https://api.github.com/users/Ajgesh/repos",
"events_url": "https://api.github.com/users/Ajgesh/events{/privacy}",
"received_events_url": "https://api.github.com/users/Ajgesh/received_events",
"type": "User",
"site_admin": false
},
{
"login": "ofonodomatt",
"id": 47601331,
"node_id": "MDQ6VXNlcjQ3NjAxMzMx",
"avatar_url": "https://avatars.githubusercontent.com/u/47601331?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/ofonodomatt",
"html_url": "https://github.com/ofonodomatt",
"followers_url": "https://api.github.com/users/ofonodomatt/followers",
"following_url": "https://api.github.com/users/ofonodomatt/following{/other_user}",
"gists_url": "https://api.github.com/users/ofonodomatt/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ofonodomatt/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ofonodomatt/subscriptions",
"organizations_url": "https://api.github.com/users/ofonodomatt/orgs",
"repos_url": "https://api.github.com/users/ofonodomatt/repos",
"events_url": "https://api.github.com/users/ofonodomatt/events{/privacy}",
"received_events_url": "https://api.github.com/users/ofonodomatt/received_events",
"type": "User",
"site_admin": false
},
{
"login": "bentech-github",
"id": 54284728,
"node_id": "MDQ6VXNlcjU0Mjg0NzI4",
"avatar_url": "https://avatars.githubusercontent.com/u/54284728?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/bentech-github",
"html_url": "https://github.com/bentech-github",
"followers_url": "https://api.github.com/users/bentech-github/followers",
"following_url": "https://api.github.com/users/bentech-github/following{/other_user}",
"gists_url": "https://api.github.com/users/bentech-github/gists{/gist_id}",
"starred_url": "https://api.github.com/users/bentech-github/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/bentech-github/subscriptions",
"organizations_url": "https://api.github.com/users/bentech-github/orgs",
"repos_url": "https://api.github.com/users/bentech-github/repos",
"events_url": "https://api.github.com/users/bentech-github/events{/privacy}",
"received_events_url": "https://api.github.com/users/bentech-github/received_events",
"type": "User",
"site_admin": false
},
{
"login": "gbetibienvenu",
"id": 64703165,
"node_id": "MDQ6VXNlcjY0NzAzMTY1",
"avatar_url": "https://avatars.githubusercontent.com/u/64703165?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/gbetibienvenu",
"html_url": "https://github.com/gbetibienvenu",
"followers_url": "https://api.github.com/users/gbetibienvenu/followers",
"following_url": "https://api.github.com/users/gbetibienvenu/following{/other_user}",
"gists_url": "https://api.github.com/users/gbetibienvenu/gists{/gist_id}",
"starred_url": "https://api.github.com/users/gbetibienvenu/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/gbetibienvenu/subscriptions",
"organizations_url": "https://api.github.com/users/gbetibienvenu/orgs",
"repos_url": "https://api.github.com/users/gbetibienvenu/repos",
"events_url": "https://api.github.com/users/gbetibienvenu/events{/privacy}",
"received_events_url": "https://api.github.com/users/gbetibienvenu/received_events",
"type": "User",
"site_admin": false
},
{
"login": "bunmijemiyo",
"id": 68944862,
"node_id": "MDQ6VXNlcjY4OTQ0ODYy",
"avatar_url": "https://avatars.githubusercontent.com/u/68944862?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/bunmijemiyo",
"html_url": "https://github.com/bunmijemiyo",
"followers_url": "https://api.github.com/users/bunmijemiyo/followers",
"following_url": "https://api.github.com/users/bunmijemiyo/following{/other_user}",
"gists_url": "https://api.github.com/users/bunmijemiyo/gists{/gist_id}",
"starred_url": "https://api.github.com/users/bunmijemiyo/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/bunmijemiyo/subscriptions",
"organizations_url": "https://api.github.com/users/bunmijemiyo/orgs",
"repos_url": "https://api.github.com/users/bunmijemiyo/repos",
"events_url": "https://api.github.com/users/bunmijemiyo/events{/privacy}",
"received_events_url": "https://api.github.com/users/bunmijemiyo/received_events",
"type": "User",
"site_admin": false
},
{
"login": "KingDayveed9c",
"id": 71224787,
"node_id": "MDQ6VXNlcjcxMjI0Nzg3",
"avatar_url": "https://avatars.githubusercontent.com/u/71224787?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/KingDayveed9c",
"html_url": "https://github.com/KingDayveed9c",
"followers_url": "https://api.github.com/users/KingDayveed9c/followers",
"following_url": "https://api.github.com/users/KingDayveed9c/following{/other_user}",
"gists_url": "https://api.github.com/users/KingDayveed9c/gists{/gist_id}",
"starred_url": "https://api.github.com/users/KingDayveed9c/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/KingDayveed9c/subscriptions",
"organizations_url": "https://api.github.com/users/KingDayveed9c/orgs",
"repos_url": "https://api.github.com/users/KingDayveed9c/repos",
"events_url": "https://api.github.com/users/KingDayveed9c/events{/privacy}",
"received_events_url": "https://api.github.com/users/KingDayveed9c/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Ellajessica",
"id": 75880259,
"node_id": "MDQ6VXNlcjc1ODgwMjU5",
"avatar_url": "https://avatars.githubusercontent.com/u/75880259?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Ellajessica",
"html_url": "https://github.com/Ellajessica",
"followers_url": "https://api.github.com/users/Ellajessica/followers",
"following_url": "https://api.github.com/users/Ellajessica/following{/other_user}",
"gists_url": "https://api.github.com/users/Ellajessica/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Ellajessica/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Ellajessica/subscriptions",
"organizations_url": "https://api.github.com/users/Ellajessica/orgs",
"repos_url": "https://api.github.com/users/Ellajessica/repos",
"events_url": "https://api.github.com/users/Ellajessica/events{/privacy}",
"received_events_url": "https://api.github.com/users/Ellajessica/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Preshfile",
"id": 79994012,
"node_id": "MDQ6VXNlcjc5OTk0MDEy",
"avatar_url": "https://avatars.githubusercontent.com/u/79994012?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Preshfile",
"html_url": "https://github.com/Preshfile",
"followers_url": "https://api.github.com/users/Preshfile/followers",
"following_url": "https://api.github.com/users/Preshfile/following{/other_user}",
"gists_url": "https://api.github.com/users/Preshfile/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Preshfile/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Preshfile/subscriptions",
"organizations_url": "https://api.github.com/users/Preshfile/orgs",
"repos_url": "https://api.github.com/users/Preshfile/repos",
"events_url": "https://api.github.com/users/Preshfile/events{/privacy}",
"received_events_url": "https://api.github.com/users/Preshfile/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Haylexking",
"id": 81008203,
"node_id": "MDQ6VXNlcjgxMDA4MjAz",
"avatar_url": "https://avatars.githubusercontent.com/u/81008203?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Haylexking",
"html_url": "https://github.com/Haylexking",
"followers_url": "https://api.github.com/users/Haylexking/followers",
"following_url": "https://api.github.com/users/Haylexking/following{/other_user}",
"gists_url": "https://api.github.com/users/Haylexking/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Haylexking/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Haylexking/subscriptions",
"organizations_url": "https://api.github.com/users/Haylexking/orgs",
"repos_url": "https://api.github.com/users/Haylexking/repos",
"events_url": "https://api.github.com/users/Haylexking/events{/privacy}",
"received_events_url": "https://api.github.com/users/Haylexking/received_events",
"type": "User",
"site_admin": false
},
{
"login": "L-caleb",
"id": 89011722,
"node_id": "MDQ6VXNlcjg5MDExNzIy",
"avatar_url": "https://avatars.githubusercontent.com/u/89011722?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/L-caleb",
"html_url": "https://github.com/L-caleb",
"followers_url": "https://api.github.com/users/L-caleb/followers",
"following_url": "https://api.github.com/users/L-caleb/following{/other_user}",
"gists_url": "https://api.github.com/users/L-caleb/gists{/gist_id}",
"starred_url": "https://api.github.com/users/L-caleb/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/L-caleb/subscriptions",
"organizations_url": "https://api.github.com/users/L-caleb/orgs",
"repos_url": "https://api.github.com/users/L-caleb/repos",
"events_url": "https://api.github.com/users/L-caleb/events{/privacy}",
"received_events_url": "https://api.github.com/users/L-caleb/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Kingicey",
"id": 89830507,
"node_id": "MDQ6VXNlcjg5ODMwNTA3",
"avatar_url": "https://avatars.githubusercontent.com/u/89830507?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Kingicey",
"html_url": "https://github.com/Kingicey",
"followers_url": "https://api.github.com/users/Kingicey/followers",
"following_url": "https://api.github.com/users/Kingicey/following{/other_user}",
"gists_url": "https://api.github.com/users/Kingicey/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Kingicey/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Kingicey/subscriptions",
"organizations_url": "https://api.github.com/users/Kingicey/orgs",
"repos_url": "https://api.github.com/users/Kingicey/repos",
"events_url": "https://api.github.com/users/Kingicey/events{/privacy}",
"received_events_url": "https://api.github.com/users/Kingicey/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Parsankamusa",
"id": 91263172,
"node_id": "MDQ6VXNlcjkxMjYzMTcy",
"avatar_url": "https://avatars.githubusercontent.com/u/91263172?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Parsankamusa",
"html_url": "https://github.com/Parsankamusa",
"followers_url": "https://api.github.com/users/Parsankamusa/followers",
"following_url": "https://api.github.com/users/Parsankamusa/following{/other_user}",
"gists_url": "https://api.github.com/users/Parsankamusa/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Parsankamusa/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Parsankamusa/subscriptions",
"organizations_url": "https://api.github.com/users/Parsankamusa/orgs",
"repos_url": "https://api.github.com/users/Parsankamusa/repos",
"events_url": "https://api.github.com/users/Parsankamusa/events{/privacy}",
"received_events_url": "https://api.github.com/users/Parsankamusa/received_events",
"type": "User",
"site_admin": false
},
{
"login": "johnkoye19",
"id": 93558021,
"node_id": "U_kgDOBZOVBQ",
"avatar_url": "https://avatars.githubusercontent.com/u/93558021?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/johnkoye19",
"html_url": "https://github.com/johnkoye19",
"followers_url": "https://api.github.com/users/johnkoye19/followers",
"following_url": "https://api.github.com/users/johnkoye19/following{/other_user}",
"gists_url": "https://api.github.com/users/johnkoye19/gists{/gist_id}",
"starred_url": "https://api.github.com/users/johnkoye19/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/johnkoye19/subscriptions",
"organizations_url": "https://api.github.com/users/johnkoye19/orgs",
"repos_url": "https://api.github.com/users/johnkoye19/repos",
"events_url": "https://api.github.com/users/johnkoye19/events{/privacy}",
"received_events_url": "https://api.github.com/users/johnkoye19/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Goddaybc",
"id": 99662106,
"node_id": "U_kgDOBfC5Gg",
"avatar_url": "https://avatars.githubusercontent.com/u/99662106?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Goddaybc",
"html_url": "https://github.com/Goddaybc",
"followers_url": "https://api.github.com/users/Goddaybc/followers",
"following_url": "https://api.github.com/users/Goddaybc/following{/other_user}",
"gists_url": "https://api.github.com/users/Goddaybc/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Goddaybc/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Goddaybc/subscriptions",
"organizations_url": "https://api.github.com/users/Goddaybc/orgs",
"repos_url": "https://api.github.com/users/Goddaybc/repos",
"events_url": "https://api.github.com/users/Goddaybc/events{/privacy}",
"received_events_url": "https://api.github.com/users/Goddaybc/received_events",
"type": "User",
"site_admin": false
},
{
"login": "ONtio-js",
"id": 103934885,
"node_id": "U_kgDOBjHrpQ",
"avatar_url": "https://avatars.githubusercontent.com/u/103934885?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/ONtio-js",
"html_url": "https://github.com/ONtio-js",
"followers_url": "https://api.github.com/users/ONtio-js/followers",
"following_url": "https://api.github.com/users/ONtio-js/following{/other_user}",
"gists_url": "https://api.github.com/users/ONtio-js/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ONtio-js/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ONtio-js/subscriptions",
"organizations_url": "https://api.github.com/users/ONtio-js/orgs",
"repos_url": "https://api.github.com/users/ONtio-js/repos",
"events_url": "https://api.github.com/users/ONtio-js/events{/privacy}",
"received_events_url": "https://api.github.com/users/ONtio-js/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Somsamsek",
"id": 106752603,
"node_id": "U_kgDOBlzqWw",
"avatar_url": "https://avatars.githubusercontent.com/u/106752603?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Somsamsek",
"html_url": "https://github.com/Somsamsek",
"followers_url": "https://api.github.com/users/Somsamsek/followers",
"following_url": "https://api.github.com/users/Somsamsek/following{/other_user}",
"gists_url": "https://api.github.com/users/Somsamsek/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Somsamsek/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Somsamsek/subscriptions",
"organizations_url": "https://api.github.com/users/Somsamsek/orgs",
"repos_url": "https://api.github.com/users/Somsamsek/repos",
"events_url": "https://api.github.com/users/Somsamsek/events{/privacy}",
"received_events_url": "https://api.github.com/users/Somsamsek/received_events",
"type": "User",
"site_admin": false
},
{
"login": "profabubakar",
"id": 106801488,
"node_id": "U_kgDOBl2pUA",
"avatar_url": "https://avatars.githubusercontent.com/u/106801488?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/profabubakar",
"html_url": "https://github.com/profabubakar",
"followers_url": "https://api.github.com/users/profabubakar/followers",
"following_url": "https://api.github.com/users/profabubakar/following{/other_user}",
"gists_url": "https://api.github.com/users/profabubakar/gists{/gist_id}",
"starred_url": "https://api.github.com/users/profabubakar/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/profabubakar/subscriptions",
"organizations_url": "https://api.github.com/users/profabubakar/orgs",
"repos_url": "https://api.github.com/users/profabubakar/repos",
"events_url": "https://api.github.com/users/profabubakar/events{/privacy}",
"received_events_url": "https://api.github.com/users/profabubakar/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Zuwairanajma",
"id": 106805225,
"node_id": "U_kgDOBl236Q",
"avatar_url": "https://avatars.githubusercontent.com/u/106805225?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Zuwairanajma",
"html_url": "https://github.com/Zuwairanajma",
"followers_url": "https://api.github.com/users/Zuwairanajma/followers",
"following_url": "https://api.github.com/users/Zuwairanajma/following{/other_user}",
"gists_url": "https://api.github.com/users/Zuwairanajma/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Zuwairanajma/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Zuwairanajma/subscriptions",
"organizations_url": "https://api.github.com/users/Zuwairanajma/orgs",
"repos_url": "https://api.github.com/users/Zuwairanajma/repos",
"events_url": "https://api.github.com/users/Zuwairanajma/events{/privacy}",
"received_events_url": "https://api.github.com/users/Zuwairanajma/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Brightator",
"id": 106819653,
"node_id": "U_kgDOBl3wRQ",
"avatar_url": "https://avatars.githubusercontent.com/u/106819653?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Brightator",
"html_url": "https://github.com/Brightator",
"followers_url": "https://api.github.com/users/Brightator/followers",
"following_url": "https://api.github.com/users/Brightator/following{/other_user}",
"gists_url": "https://api.github.com/users/Brightator/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Brightator/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Brightator/subscriptions",
"organizations_url": "https://api.github.com/users/Brightator/orgs",
"repos_url": "https://api.github.com/users/Brightator/repos",
"events_url": "https://api.github.com/users/Brightator/events{/privacy}",
"received_events_url": "https://api.github.com/users/Brightator/received_events",
"type": "User",
"site_admin": false
},
{
"login": "DinoTech01",
"id": 106820637,
"node_id": "U_kgDOBl30HQ",
"avatar_url": "https://avatars.githubusercontent.com/u/106820637?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/DinoTech01",
"html_url": "https://github.com/DinoTech01",
"followers_url": "https://api.github.com/users/DinoTech01/followers",
"following_url": "https://api.github.com/users/DinoTech01/following{/other_user}",
"gists_url": "https://api.github.com/users/DinoTech01/gists{/gist_id}",
"starred_url": "https://api.github.com/users/DinoTech01/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/DinoTech01/subscriptions",
"organizations_url": "https://api.github.com/users/DinoTech01/orgs",
"repos_url": "https://api.github.com/users/DinoTech01/repos",
"events_url": "https://api.github.com/users/DinoTech01/events{/privacy}",
"received_events_url": "https://api.github.com/users/DinoTech01/received_events",
"type": "User",
"site_admin": false
},
{
"login": "MisCynthia",
"id": 106990543,
"node_id": "U_kgDOBmCLzw",
"avatar_url": "https://avatars.githubusercontent.com/u/106990543?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MisCynthia",
"html_url": "https://github.com/MisCynthia",
"followers_url": "https://api.github.com/users/MisCynthia/followers",
"following_url": "https://api.github.com/users/MisCynthia/following{/other_user}",
"gists_url": "https://api.github.com/users/MisCynthia/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MisCynthia/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MisCynthia/subscriptions",
"organizations_url": "https://api.github.com/users/MisCynthia/orgs",
"repos_url": "https://api.github.com/users/MisCynthia/repos",
"events_url": "https://api.github.com/users/MisCynthia/events{/privacy}",
"received_events_url": "https://api.github.com/users/MisCynthia/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Oyekent",
"id": 107007437,
"node_id": "U_kgDOBmDNzQ",
"avatar_url": "https://avatars.githubusercontent.com/u/107007437?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Oyekent",
"html_url": "https://github.com/Oyekent",
"followers_url": "https://api.github.com/users/Oyekent/followers",
"following_url": "https://api.github.com/users/Oyekent/following{/other_user}",
"gists_url": "https://api.github.com/users/Oyekent/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Oyekent/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Oyekent/subscriptions",
"organizations_url": "https://api.github.com/users/Oyekent/orgs",
"repos_url": "https://api.github.com/users/Oyekent/repos",
"events_url": "https://api.github.com/users/Oyekent/events{/privacy}",
"received_events_url": "https://api.github.com/users/Oyekent/received_events",
"type": "User",
"site_admin": false
},
{
"login": "mikeol1",
"id": 107035220,
"node_id": "U_kgDOBmE6VA",
"avatar_url": "https://avatars.githubusercontent.com/u/107035220?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/mikeol1",
"html_url": "https://github.com/mikeol1",
"followers_url": "https://api.github.com/users/mikeol1/followers",
"following_url": "https://api.github.com/users/mikeol1/following{/other_user}",
"gists_url": "https://api.github.com/users/mikeol1/gists{/gist_id}",
"starred_url": "https://api.github.com/users/mikeol1/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/mikeol1/subscriptions",
"organizations_url": "https://api.github.com/users/mikeol1/orgs",
"repos_url": "https://api.github.com/users/mikeol1/repos",
"events_url": "https://api.github.com/users/mikeol1/events{/privacy}",
"received_events_url": "https://api.github.com/users/mikeol1/received_events",
"type": "User",
"site_admin": false
},
{
"login": "jentrixwameya",
"id": 107076449,
"node_id": "U_kgDOBmHbYQ",
"avatar_url": "https://avatars.githubusercontent.com/u/107076449?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/jentrixwameya",
"html_url": "https://github.com/jentrixwameya",
"followers_url": "https://api.github.com/users/jentrixwameya/followers",
"following_url": "https://api.github.com/users/jentrixwameya/following{/other_user}",
"gists_url": "https://api.github.com/users/jentrixwameya/gists{/gist_id}",
"starred_url": "https://api.github.com/users/jentrixwameya/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/jentrixwameya/subscriptions",
"organizations_url": "https://api.github.com/users/jentrixwameya/orgs",
"repos_url": "https://api.github.com/users/jentrixwameya/repos",
"events_url": "https://api.github.com/users/jentrixwameya/events{/privacy}",
"received_events_url": "https://api.github.com/users/jentrixwameya/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Hapizeekem",
"id": 107250899,
"node_id": "U_kgDOBmSE0w",
"avatar_url": "https://avatars.githubusercontent.com/u/107250899?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Hapizeekem",
"html_url": "https://github.com/Hapizeekem",
"followers_url": "https://api.github.com/users/Hapizeekem/followers",
"following_url": "https://api.github.com/users/Hapizeekem/following{/other_user}",
"gists_url": "https://api.github.com/users/Hapizeekem/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Hapizeekem/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Hapizeekem/subscriptions",
"organizations_url": "https://api.github.com/users/Hapizeekem/orgs",
"repos_url": "https://api.github.com/users/Hapizeekem/repos",
"events_url": "https://api.github.com/users/Hapizeekem/events{/privacy}",
"received_events_url": "https://api.github.com/users/Hapizeekem/received_events",
"type": "User",
"site_admin": false
}
]